abstract class AppStates{}
class AppInitialState extends AppStates{}
class AppChangeNavBarState extends AppStates{}
class AppCreateDatabaseState extends AppStates{}
class AppInsertDatabaseState extends AppStates{}
class AppGetDatabaseState extends AppStates{}
class AppUpdateDatabaseState extends AppStates{}
class AppGetDatabaseLoadingState extends AppStates{}
class AppNotLoadingState extends AppStates{}
class AppLoadingState extends AppStates{}
class AppCheckState extends AppStates{}
class AppNotCheckState extends AppStates{}
class AppCoordinateDoneState extends AppStates{}
class AppCoordinateErrorState extends AppStates{}
class AppGetTimesLoadingState extends AppStates{}
class AppGetTimesDoneState extends AppStates{}
class AppGetTimesErrorState extends AppStates{}
class AppChangePageState extends AppStates{}
class AppGetSaveSafhaState extends AppStates{}